server:
    port: 8082

spring:
    profiles:
      active: qa

---


spring:
    profiles: qa
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: nxd2022
        url: jdbc:mysql://localhost:3306/SpringBootDB
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Spring Boot from qa database

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---


spring:
    profiles: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: nxd2022
        url: jdbc:mysql://localhost:3306/SpringBootDB-dev
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Spring Boot from dev database

---


spring:
    profiles: prod
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: nxd2022
        url: jdbc:mysql://localhost:3306/SpringBootDB-prod
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Spring Boot from prod database
